// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OperationLibrary.Entity;

public partial class EmailLog
{
    public int ID { get; set; }

    public string To { get; set; }

    public string Cc { get; set; }

    public string Bcc { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public DateTime CreateTime { get; set; }

    public DateTime? SendTime { get; set; }
}