// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using OperationLibrary.Entity;

namespace OperationLibrary.Operation.DbContext;

public partial class EmailApiDbContext : Microsoft.EntityFrameworkCore.DbContext
{
    public EmailApiDbContext(DbContextOptions<EmailApiDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<EmailLog> EmailLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS");

        modelBuilder.Entity<EmailLog>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__EmailLog__3214EC2706AA0B5B");

            entity.ToTable("EmailLog");

            entity.Property(e => e.Body).IsRequired();
            entity.Property(e => e.CreateTime).HasColumnType("datetime");
            entity.Property(e => e.SendTime).HasColumnType("datetime");
            entity.Property(e => e.Subject).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
