

ALTER TABLE [OFS_CUL_Project] ADD [Organizer] INT NOT NULL DEFAULT 0
GO

ALTER TABLE [OFS_EDC_Project] ADD [Organizer] INT NOT NULL DEFAULT 0
GO

ALTER TABLE [OFS_MUL_Project] ADD [Organizer] INT NOT NULL DEFAULT 0
GO

ALTER TABLE [OFS_LIT_Project] ADD [Organizer] INT NOT NULL DEFAULT 0
GO

ALTER TABLE [OFS_ACC_Project] ADD [Organizer] INT NOT NULL DEFAULT 0
GO


